### ISSUE TITLE
'Select A Module' Dropdown - css width property

### ISSUE THREAD

**Issue by teisenhower** [publiclab/image-sequencer#1044]
The width of the dropdown containing the modules is set to a `vw` value in the css. This results in the dropdown growing and shrinking depending on the width of the browser window. Causing it to extend beyond where it should covering up the "Add Step" button.

I was able to fix this by removing the `width: 24vw;` from `.selectize-input`

This code lives in `examples->selectize.default.css` and the width value is on line `139`
````css
.selectize-input {
  border: 1px solid #d0d0d0;
  padding: 10px 0px;
  display: inline-block;
  width: 24vw;
  overflow: hidden;
  position: relative;
  z-index: 1;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.1);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.1);
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
}
````    
This exists within the Latest Stable Demo: https://sequencer.publiclab.org

![dropdown](https://user-images.githubusercontent.com/47988669/56815750-12760280-6810-11e9-9c87-c67b128bbe39.PNG)

![dropdownMenu](https://user-images.githubusercontent.com/47988669/56816881-65e95000-6812-11e9-9c25-b5667fc92568.gif)

This should be an easy first-timer issue. 

**Thanks!**

**Comment by jywarren** [comment]
Oh, this is great! So, does the solution then scale to multiple widths?
this is indeed something I've been hoping we can fix. Thank you!

**Comment by teisenhower** [comment]
Of course! Happy to help out!

The simple solution of just removing that width property outlined above won't enable it to scale to different widths, it'll be locked to whatever other css is setting the width. However, we could absolutely implement another solution that allows the width to be dynamic while still containing it to fit within the box and not overlap the button. If that's what you're looking for. 

Thanks!!

**Comment by teisenhower** [comment]
Hey! 

Here is something I worked up if you did want multiple widths. This involves altering the CSS a little bit and also changing some of the Bootstrap column classes in the index. But this will allow the "Select A Module" dropdown and "Add Step" button to scale depending on the width of the browser window.

---

## Full Browser
(large breakpoint)
![Full](https://user-images.githubusercontent.com/47988669/56850588-c6d85d00-68d2-11e9-8dca-3fe4062930a9.png)

## Large Breakpoint
![lg](https://user-images.githubusercontent.com/47988669/56850619-00a96380-68d3-11e9-9db2-c33d57a2e6f8.png)


## Medium Breakpoint
![md](https://user-images.githubusercontent.com/47988669/56850601-eec7c080-68d2-11e9-9893-da6074d0f13d.png)

## Small Breakpoint
![sm](https://user-images.githubusercontent.com/47988669/56850603-f25b4780-68d2-11e9-817e-c7ccdc619321.png)

## XSmall Breakpoint
![xsm](https://user-images.githubusercontent.com/47988669/56850604-f5eece80-68d2-11e9-80e6-0411d7584dc5.png)

## GIF Example 
![breakpointSteps](https://user-images.githubusercontent.com/47988669/56850446-e2daff00-68d0-11e9-8d17-1afa19ea7421.gif)




---
This would also eliminate this from happening on smaller screens. Where the "arrow" icon gets pushed into the text.
![currentDropdown](https://user-images.githubusercontent.com/47988669/56850509-c4c1ce80-68d1-11e9-9cf5-0fdaca4d5ada.PNG)

**Comment by HarshKhandeparkar** [comment]
@teisenhower are you going to open a PR?

**Comment by HarshKhandeparkar** [comment]
Btw, please don't change the lib file `selectize.default.css` directly. Instead, you can add a rule to `demo.css` and add the `!important`

**Comment by teisenhower** [comment]
Hey! I can but I was also going to see if you guys wanted to make this a first timers only issue.

**Comment by HarshKhandeparkar** [comment]
You can do that too!
Just open the *file*(single) you want to edit, in the broswer. Make the
changes. It will ask you the new branch name, just prepend `first-timers-`
to the branch name. E.g. `first-timers-selectize-fix`. A new FTO will be
created! Try it!

**Comment by teisenhower** [comment]
Awesome! I'll be sure to do that as soon as I get home today. Thanks!

**Comment by HarshKhandeparkar** [comment]
Great! Thanks a ton!

**Comment by teisenhower** [comment]
@HarshKhandeparkar Do I need to edit the code in my fork or the main repo? I started doing it on the main repo and it wants me to make a PR. Is that what I should do?

**Comment by HarshKhandeparkar** [comment]
Just don't open the PR, the issue will still be created

**Comment by HarshKhandeparkar** [comment]
Make it on the main repo.

**Comment by teisenhower** [comment]
Sorry for the confusion, it is having me compare the changes between 2 branches, not create a new branch. 

![Capture](https://user-images.githubusercontent.com/47988669/56868349-47748780-69bf-11e9-8fad-d40b7dbe5699.PNG)

**Comment by HarshKhandeparkar** [comment]
OK, sorry for the trouble:
1. Edit the file here https://github.com/publiclab/image-sequencer/edit/main/examples/demo.css
2. Commit names do not matter, only the branch name does
![Screenshot_2019-04-28 publiclab image-sequencer](https://user-images.githubusercontent.com/34770591/56868385-731f5e00-6a0f-11e9-8dc2-89818e1f542f.png)
See this at the very end of the page? See the `create a new branch` option, add `first-timers-*` in there(`*` being anything descriptive). Click on the `commit changes` or `propose changes` button.
3. If it redirects you to a create pull request page, just close the tab.

**Comment by teisenhower** [comment]
I do not have that at the bottom of my page. I just have a "propose file change" form. I don't have the option of creating a new branch. I was just looking into this, not sure why I am not seeing that option. 

![Capture](https://user-images.githubusercontent.com/47988669/56868443-7ccda500-69c0-11e9-99e1-abfcd481dbee.PNG)

I am getting this alert at the top of that edit page, saying I don't have write access to

![Capture2](https://user-images.githubusercontent.com/47988669/56868509-40e70f80-69c1-11e9-8a42-0f06911c728c.PNG)


I apologize for the added hassle on this

**Comment by HarshKhandeparkar** [comment]
One last thing, try editing the file a little bit?

**Comment by HarshKhandeparkar** [comment]
Oh absolutely sorry for the trouble, I thought anybody could do that. Ok I will do that myself, could you please tell me what to change/add?

**Comment by teisenhower** [comment]
No worries!! I just wanted to make sure I was doing everything the way you guys need. 

## Here are the changes made to the `demo.css` file 
### starting at line 105

````css 
#add-step-btn{
  /* margin-left needed to be removed in order to solve column width issue #1044*/
  /* margin-left: 10px; */
  /* width added to solve the column width issue #1044*/
  width: 100% !important;
}
````   

### added to end of file    

````css     
.selectize-input {
  /* width added to solve the column width issue #1044*/
  /* cancels out the width:24vw in selectize.default.css - issue #1044*/
  width: 100% !important;
}
```` 
----
## Then there are some minor class changes to be made in the `index.html` file
These lines are 140-150
- We are adding `justify-content-center` to the row containing the dropdown and add step button
- Adding `text-center` class to the `select` group. This keeps all the elements inside the dropdown center justified. 
- Then finally on the divs containing the dropdown and add step button we are changing the col classes. This is what allows their widths to change depending on the window size.  
#### Proposed changes to index.html
````html
<div class="row justify-content-center">
    <div class="col-lg-8">

        <select id="selectStep" class="text-center">
            <!-- The default null selection has been appended manually in demo.js
              This is because the options in select are overritten when options are appended.-->
        </select>
    </div>
    <div class="col-lg-4">
        <button class="btn btn-success btn-lg" name="add" id="add-step-btn">Add Step</button></div>
</div>
```` 
#### Current index.html
````html
<div class="row center-align">
    <div class="col-md-8">

        <select id="selectStep">
            <!-- The default null selection has been appended manually in demo.js
  This is because the options in select are overritten when options are appended.-->
        </select>
    </div>
    <div class="col-md-4">
        <button class="btn btn-success btn-lg" name="add" id="add-step-btn">Add Step</button></div>
</div>
````
